<?php

    return array(
        'cache'=>array(
            'Yac'=>array(),
            'Apc'=>array(),
            'Xcache'=>array(),
            'Redis'=>array(
                'name'=>'cache',
                'pconnect'=>true,
                'host'=>'127.0.0.1',
                'port'=>6379,
                'timeout'=>5
            ),
            'Memcached'=>array(
                'name'=>'cache',
                'pconnect'=>true,
                'servers'=>array(
                    array(
                        'host'=>'127.0.0.1',
                        'port'=>11211
                    ),
                    array(
                        'host'=>'127.0.0.1',
                        'port'=>11212
                    )
                )
            )
        ),
    );
